# Generated by Django 3.1 on 2020-11-28 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openslides_cfg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openslidesinstance',
            name='admin_email',
        ),
        migrations.RemoveField(
            model_name='openslidesinstance',
            name='admin_name',
        ),
        migrations.RemoveField(
            model_name='openslidesinstance',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='openslidesinstance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2020-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openslidesinstance',
            name='created_by',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
