# Generated by Django 3.1 on 2020-11-29 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openslides_cfg', '0003_auto_20201128_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='openslidesinstance',
            name='email_default_from',
            field=models.EmailField(default='', max_length=254, verbose_name='E-Mail default Absender'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openslidesinstance',
            name='email_password',
            field=models.CharField(default='', max_length=255, verbose_name='E-Mail Server Passwort'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openslidesinstance',
            name='email_server',
            field=models.CharField(default='', max_length=255, verbose_name='E-Mail Server'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openslidesinstance',
            name='email_server_port',
            field=models.IntegerField(default=587, verbose_name='E-Mail Server-Portnummer'),
        ),
        migrations.AddField(
            model_name='openslidesinstance',
            name='email_username',
            field=models.CharField(default='', max_length=255, verbose_name='E-Mail Server Benutzername'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openslidesinstance',
            name='enable_electronic_voting',
            field=models.BooleanField(default=True, verbose_name='Elektronische Wahlen erlauben?'),
        ),
        migrations.AddField(
            model_name='openslidesinstance',
            name='meet_password',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openslidesinstance',
            name='reset_password_verbose',
            field=models.BooleanField(default=True, verbose_name='Aussagekrägtige Fehlermeldung beim Passwort zurücksetzen?'),
        ),
        migrations.AlterField(
            model_name='openslidesinstance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='openslidesinstance',
            name='created_by',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mymodels', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='openslidesinstance',
            name='meet_room',
            field=models.CharField(max_length=30, verbose_name='Jitsi Meet Raumname'),
        ),
        migrations.AlterField(
            model_name='openslidesinstance',
            name='name_text',
            field=models.CharField(max_length=30, verbose_name='OpenSlides Name'),
        ),
        migrations.AlterField(
            model_name='openslidesinstance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last update on'),
        ),
        migrations.AlterField(
            model_name='openslidesinstance',
            name='updated_by',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mymodels2', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
    ]
