# Generated by Django 3.1 on 2020-11-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openslides_cfg', '0005_auto_20201129_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='openslidesinstance',
            name='install_status',
            field=models.CharField(default='0', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='openslidesinstance',
            name='meet_password',
            field=models.CharField(blank=True, max_length=40, verbose_name='Jitsi Meet Raumpasswort (sofern vergeben)'),
        ),
    ]
